# Generated by Django 5.0.2 on 2024-02-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(default=0, unique=True, verbose_name='ID пользователя в телеграме')),
                ('phone_number', models.CharField(default=0, max_length=12, verbose_name='Номер телефона')),
                ('username', models.CharField(default='', max_length=40, verbose_name='Ник в телеге')),
                ('first_name', models.CharField(default='', max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=40, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
