# Generated by Django 5.0.2 on 2024-02-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='adminuser',
            name='external_id',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='ID пользователя в телеграме'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='phone_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер телефона'),
        ),
    ]
