# Generated by Django 5.0.2 on 2024-02-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_adminuser_options_adminuser_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(default=0, max_length=12, verbose_name='Номер телефона'),
        ),
    ]
